### ISSUE TITLE
 Update the `example_synthetic` files

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/neurobagel_examples#18]
Once https://github.com/neurobagel/annotation_tool/issues/597 is closed, update the `example_synthetic` files using the files in the annotation tool under `cypress/fixtures/examples/good`

**Comment by rmanaem** [comment]
@alyssadai Aside from [example_synthetic.json](https://github.com/neurobagel/neurobagel_examples/blob/main/data-upload/example_synthetic.json) having to be replaced with [the one from annotation tool](https://github.com/neurobagel/annotation_tool/blob/master/cypress/fixtures/examples/good/example_synthetic.json), and adding the [example_synthetic_expected_output.json](https://github.com/neurobagel/annotation_tool/blob/master/cypress/fixtures/examples/good/example_synthetic_expected_output.json) is there anything else that needs to updated?

**Comment by alyssadai** [comment]
Hey @rmanaem,

To avoid having to change the file names in the other tools that use this example set (e.g., the CLI), here's my suggestion:
- Add https://github.com/neurobagel/annotation_tool/blob/master/cypress/fixtures/examples/good/example_synthetic.json to the `data-upload/` folder but give it a different name, such as `example_synthetic_participants.json`  since it's meant to represent the pre-Neurobagel BIDS `participants.json` for this dataset
- Replace `example_synthetic.json` in this repo with [example_synthetic_expected_output.json](https://github.com/neurobagel/annotation_tool/blob/master/cypress/fixtures/examples/good/example_synthetic_expected_output.json) but keep the same original name

Let me know if that makes sense!

**Comment by rmanaem** [comment]
Sounds good!
