### ISSUE TITLE
Replace OpenNeuro sample .ttl files with synthetic example data

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/neurobagel_examples#2]
To turn this repo into the single location of our comprehensive reference examples (for docs, other tools, etc.), the two existing .ttl files (likely out of date with our current data model) will be replaced by the following files from https://github.com/neurobagel/bagel-cli/tree/main/bagel/tests/data:
- example_synthetic.tsv
- example_synthetic.json
- example_synthetic.jsonld --> maybe rename to example_synthetic_pheno.jsonld?
  - [ ] since this file will not be used for our test graph (just as an example of a jsonld with only phenotypic data), maybe store it in a separate directory for easier automation of the push-to-graph step
- example_synthetic_pheno-bids.jsonld

**Comment by rmanaem** [comment]
@alyssadai 
> since this file will not be used for our test graph (just as an example of a jsonld with only phenotypic data), maybe store it in a separate directory for easier automation of the push-to-graph step

Given this repo is going to house various examples I think it's better to store the other 3 files (and any future files) in a directory for easier automation. wdyt?
